name: Debug gh actions

on:
  check_run: 
    types: [ completed ]

jobs:
  debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - run: |
          echo "Name: ${{ github.event.check_run.app.name }}"
          echo "Conclusion: ${{ github.event.check_run.conclusion }}"
          echo "Name: ${{ github.event.check_run.name }}"
