name: Debug gh actions

on:
  check_suite: 
    types: [ completed ]
  
jobs:
  debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - run: |
          echo "Conclusion: ${{ github.event.check_suite.conclusion }}"
          echo "Name: ${{ github.event.check_suite.name }}"
